// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';
import {invite} from '../models';
import {main} from '../models';
import {netif} from '../models';
import {protocol} from '../models';
import {staging} from '../models';

export function CancelIncoming():Promise<void>;

export function CancelOutgoing():Promise<void>;

export function ChatHistory(arg1:string):Promise<Array<chat.Message>>;

export function DownloadsPath():Promise<string>;

export function GenerateInvite():Promise<invite.Bundle>;

export function ImportInviteFile():Promise<main.ImportInviteResult>;

export function Interfaces():Promise<Array<netif.NetInterface>>;

export function LogPath():Promise<string>;

export function MarkRead(arg1:string):Promise<void>;

export function OpenFilePicker():Promise<Array<string>>;

export function OpenFolderPicker():Promise<string>;

export function Peers():Promise<Array<protocol.DeviceInfo>>;

export function RespondIncoming(arg1:boolean):Promise<void>;

export function RevealDownloads():Promise<void>;

export function SaveInviteBundle(arg1:invite.Bundle):Promise<string>;

export function SaveInviteFile():Promise<string>;

export function SaveInvitePNG():Promise<string>;

export function ScanPaths(arg1:Array<string>):Promise<Array<staging.Entry>>;

export function SelfInfo():Promise<protocol.DeviceInfo>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;

export function SendTo(arg1:string,arg2:Array<protocol.SendItem>):Promise<void>;

export function StartEngine(arg1:string):Promise<void>;
