// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelIncoming() {
  return window['go']['main']['App']['CancelIncoming']();
}

export function CancelOutgoing() {
  return window['go']['main']['App']['CancelOutgoing']();
}

export function ChatHistory(arg1) {
  return window['go']['main']['App']['ChatHistory'](arg1);
}

export function DownloadsPath() {
  return window['go']['main']['App']['DownloadsPath']();
}

export function Interfaces() {
  return window['go']['main']['App']['Interfaces']();
}

export function MarkRead(arg1) {
  return window['go']['main']['App']['MarkRead'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function OpenFolderPicker() {
  return window['go']['main']['App']['OpenFolderPicker']();
}

export function Peers() {
  return window['go']['main']['App']['Peers']();
}

export function RespondIncoming(arg1) {
  return window['go']['main']['App']['RespondIncoming'](arg1);
}

export function RevealDownloads() {
  return window['go']['main']['App']['RevealDownloads']();
}

export function ScanPaths(arg1) {
  return window['go']['main']['App']['ScanPaths'](arg1);
}

export function SelfInfo() {
  return window['go']['main']['App']['SelfInfo']();
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SendTo(arg1, arg2) {
  return window['go']['main']['App']['SendTo'](arg1, arg2);
}

export function StartEngine(arg1) {
  return window['go']['main']['App']['StartEngine'](arg1);
}
